### ISSUE TITLE
'module' object has no attribute 's'

### ISSUE THREAD

**Issue by whites11** [gtozzi/pysmartinfo#1]
Hi,

trying to run the test.py script with both python2 and python3.
I installed the `attr` and `serial` modules with `pip` but I get this error:

```
python3 test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    import smartinfo
  File "/opt/smartinfo/smartinfo/__init__.py", line 24, in <module>
    from . import ab
  File "/opt/smartinfo/smartinfo/ab.py", line 42, in <module>
    @attr.s(frozen=True)
AttributeError: 'module' object has no attribute 's'
```

Any idea how I can solve it?

**Comment by gtozzi** [comment]
You probably have a too old version of the attrs module.
Did you try updating it?

**Comment by whites11** [comment]
Don't think so, just installed it via pip.
Will report the version.

**Comment by whites11** [comment]
Here it is:
```
$ pip3 list
attr (0.3.1)
```
Too old?

**Comment by erosinnocenti** [comment]
I think the correct module name is `attrs`, not `attr`.
